# Generated by Django 2.0.4 on 2018-04-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cucumber', '오이')], default='cucumber', max_length=50, verbose_name='품목')),
                ('price', models.SmallIntegerField(verbose_name='가격')),
                ('date', models.DateField(verbose_name='기준일')),
            ],
            options={
                'verbose_name': '채소 가격들',
                'db_table': 'price',
            },
        ),
    ]
