# Generated by Django 2.0.4 on 2018-04-07 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='unit',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='단위'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=50, verbose_name='품목'),
        ),
    ]
