# Generated by Django 2.0.4 on 2018-04-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_auto_20180407_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': '채소 가격', 'verbose_name_plural': '채소 가격들'},
        ),
    ]
