# Generated by Django 2.0.4 on 2018-04-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, verbose_name='아이디')),
                ('provider', models.CharField(choices=[('d', '디프만'), ('k', '카카오')], default='d', max_length=2, verbose_name='가입 경로')),
                ('uid', models.CharField(max_length=255, verbose_name='소셜 유저 유니크 아이디')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='휴대전화')),
                ('is_acitve', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저들',
                'db_table': 'user',
            },
        ),
    ]
