# Generated by Django 2.0.4 on 2018-04-07 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payment', models.BooleanField(default=True, verbose_name='지불완료')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='회식 제목')),
                ('total', models.IntegerField(verbose_name='전체 금액')),
                ('is_payment', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('create_At', models.DateTimeField(verbose_name='생성 날짜')),
                ('member', models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='참여자')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='주최자')),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partys.Party', verbose_name='회식'),
        ),
        migrations.AddField(
            model_name='billing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='지불자'),
        ),
    ]
