# Generated by Django 2.0.4 on 2018-04-07 06:00

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='create_At',
        ),
        migrations.AddField(
            model_name='party',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성 날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='주최 날짜'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='참여자'),
        ),
    ]
