# Generated by Django 2.0.4 on 2018-04-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='count',
            field=models.SmallIntegerField(default=0, verbose_name='인원수'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='result',
            field=models.IntegerField(default=0, verbose_name='엔빵 금액'),
            preserve_default=False,
        ),
    ]
